version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - echo "Listing files"
      - pwd
      - ls -R
      - dotnet --version
      - dotnet restore

  build:
    commands:
      - dotnet publish -c Release -o publish

artifacts:
  files:
    - '**/*'
  base-directory: publish
