version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - cd sample-api
      - dotnet restore

  build:
    commands:
      - dotnet publish -c Release -o publish

artifacts:
  files:
    - '**/*'
  base-directory: sample-api/publish
